# Generated by Django 3.0 on 2022-01-14 02:41

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigurationM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_facebook_url', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Page of Facebook')),
                ('page_twitter_url', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Page of Twitter')),
                ('page_instagram_url', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Page of Instagram')),
                ('location', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
