# Generated by Django 3.0 on 2022-02-06 03:14

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigurationm',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Ubicacion'),
        ),
    ]
