# Generated by Django 3.0 on 2022-01-14 02:51

import commons.models.site_configuration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfigurationm',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Sites Configurations'},
        ),
        migrations.AddField(
            model_name='siteconfigurationm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=commons.models.site_configuration.create_path_category, verbose_name='Icon'),
        ),
    ]
