# Generated by Django 3.0 on 2022-01-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20220113_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfigurationm',
            options={'verbose_name': 'Sitio de configuación', 'verbose_name_plural': 'Sitio de configuraciónes'},
        ),
    ]
